import { StyleSheet } from 'react-native';
import { COLORS } from '../config/colors';

export const commonStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: COLORS.background },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 15,
    paddingVertical: 12,
    backgroundColor: COLORS.headerBg,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.primaryDark,
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 18,
    fontWeight: '700',
    color: COLORS.textOnPrimary,
  },
  backBtn: { padding: 5, minWidth: 40 },
  backBtnText: { fontSize: 24, color: COLORS.textOnPrimary, fontWeight: '600' },
  backBtnTextSmall: { fontSize: 16, color: COLORS.textOnPrimary, fontWeight: '500' },
  headerRight: { minWidth: 40, alignItems: 'flex-end' },
  formContainer: { flex: 1, padding: 15 },
  formCard: {
    backgroundColor: COLORS.cardBg,
    borderRadius: 16,
    padding: 20,
    marginBottom: 30,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  label: {
    fontSize: 13,
    fontWeight: '600',
    color: COLORS.primary,
    marginBottom: 6,
    marginTop: 14,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  input: {
    backgroundColor: COLORS.inputBg,
    padding: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: COLORS.border,
    fontSize: 16,
    color: COLORS.textPrimary,
  },
  textArea: { minHeight: 80, textAlignVertical: 'top', paddingTop: 14 },
  pickerBtn: {
    backgroundColor: COLORS.inputBg,
    padding: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: COLORS.border,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  pickerBtnText: { fontSize: 16, color: COLORS.textPrimary },
  pickerBtnIcon: { fontSize: 20 },
  primaryButton: {
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 20,
    backgroundColor: COLORS.primary,
  },
  primaryButtonText: { color: COLORS.textOnPrimary, fontSize: 17, fontWeight: '700' },
  primaryButtonDisabled: { opacity: 0.6 },
  modalOverlay: {
    flex: 1,
    backgroundColor: COLORS.overlay,
    justifyContent: 'center',
    alignItems: 'center',
  },
  contextMenu: {
    backgroundColor: COLORS.cardBg,
    borderRadius: 15,
    padding: 10,
    width: 260,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  contextMenuItem: { paddingVertical: 14, paddingHorizontal: 20 },
  contextMenuText: { fontSize: 16, color: COLORS.textPrimary },
  contextMenuTextActive: { color: COLORS.primary, fontWeight: '700' },
  loader: { marginTop: 50 },
  emptyText: { textAlign: 'center', color: COLORS.textLight, fontSize: 15, marginTop: 60 },
});
